name: PlatformIO CI ESP32

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
        - "3.8"

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.platformio
        key: ${{ runner.os }}-python${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade platformio
        platformio update

        # Ethernet library
        platformio lib -g install 872
        # Compact Bluetooth Low Energy library 
        platformio lib install h2zero/NimBLE-Arduino@^1.4.0

    - name: Setup config
      run: |
        rm -R BSB_LAN/src/WiFiSpi
        rm -R BSB_LAN/src/Time
        cp BSB_LAN/BSB_LAN_config.h.default BSB_LAN/BSB_LAN_config.h
        cp BSB_LAN/BSB_LAN_custom_defs.h.default BSB_LAN/BSB_LAN_custom_defs.h

    - name: Run PlatformIO CI
      run: platformio ci --project-option="platform = https://github.com/platformio/platform-espressif32.git" --project-option="board_build.partitions = huge_app.csv" --board=esp32-evb ./BSB_LAN
